en:
  omniauth_callbacks:
    authentication_error: 'Authentication error has occured.'
